# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

sass:
  sass_dir: _sass
  style: compressed #expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

# SEO settings
title: Cabras Beer
description: "Sitio en construcción"
keywords: "cabras, beer, cerveza, beeer, uruguay"

# Site settings
url: "http://www.cabrasbeeer.com"

include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]

#algolia:
#  index_name: blog
#  application_id: 'Z1MEP1W19K'
#  search_only_api_key: 76c1a415cbb8523bc01cf846aa546c22

collections:
  equipo:
    output: true
  cervezas:
    output: true

#baseurl: "/dotX"
# baseurl: ""

# Author settings
#author:
#  name      : Fernando Moreira
#  job       : Frontend Engineer
#  bio       : "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
#  thumb     : /images/author.jpg
#  email     : nandomoreira.me@gmail.com
#  url       : http://nandomoreira.me
  #  github    :
  #  twitter   : http://twitter.com/nandomoreirame
  #  facebook  : http://facebook.com/fernando.dev
  #  linkedin  : http://linkedin.com/in/nandomoreirame

# google_analytics: UA-52446115-1
#repo: http://github.com/cabrasbeeer/blog

# comments
#disqus_shortname: "fernandomoreira"
